public class ManageProductsForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageProductsForm.class.getName());

    /**
     * Creates new form ManageProductsForm
     */
    public ManageProductsForm() {
        initComponents();
        
        // Set product categories in the ComboBox
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[]{
                "Casual Wear",
                "Formal Wear",
                "Sportswear",
                "Footwear",
                "Accessories"
            }
        ));

        // Load products from the database
        loadProducts();

        setLocationRelativeTo(null);
    }
    
    private String getCategoryName(int categoryID) {

        switch (categoryID) {

            case 1:
                return "Casual Wear";

            case 2:
                return "Formal Wear";

            case 3:
                return "Sportswear";

            case 4:
                return "Footwear";

            case 5:
                return "Accessories";

            default:
                return "Unknown";
        }
    }
    
    private int getCategoryID(String categoryName) {

        switch (categoryName) {

            case "Casual Wear":
                return 1;

            case "Formal Wear":
                return 2;

            case "Sportswear":
                return 3;

            case "Footwear":
                return 4;

            case "Accessories":
                return 5;

            default:
                return 1;
        }
    }
    
    private void clearFields() {

    txtProductID.setText("");
    txtProductName.setText("");
    txtBrand.setText("");
    txtSize.setText("");
    txtColor.setText("");
    txtPrice.setText("");
    txtStock.setText("");

    // Set Category ComboBox to the first category
    if (cmbCategory.getItemCount() > 0) {
        cmbCategory.setSelectedIndex(0);
    }

    txtProductName.requestFocus();
    }
    
    private void loadProducts() {

    dao.ProductDAO productDAO = new dao.ProductDAO();

    java.util.ArrayList<model.Product> products =
            productDAO.getAllProducts();

    javax.swing.table.DefaultTableModel tableModel =
            (javax.swing.table.DefaultTableModel) tblProducts.getModel();

    // Remove old rows before loading fresh data
    tableModel.setRowCount(0);

        for (model.Product product : products) {

            String categoryName =
                    getCategoryName(product.getCategoryID());

            tableModel.addRow(new Object[]{
                product.getProductID(),
                product.getProductName(),
                product.getBrand(),
                categoryName,
                product.getSize(),
                product.getColor(),
                product.getPrice(),
                product.getStockQuantity()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnUpdateProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        txtStock = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        btnViewProducts = new javax.swing.JButton();
        txtProductID = new javax.swing.JTextField();
        btnDeleteProduct = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        cmbCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Brand");
        jLabel3.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Price");

        btnUpdateProduct.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnUpdateProduct.setText("Update Product");
        btnUpdateProduct.addActionListener(this::btnUpdateProductActionPerformed);

        tblProducts.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Brand", "Category", "Size", "Colour", "Price", "Stock"
            }
        ));
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        txtStock.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtBrand.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtBrand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBrand.addActionListener(this::txtBrandActionPerformed);

        btnViewProducts.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnViewProducts.setText("View Products");
        btnViewProducts.addActionListener(this::btnViewProductsActionPerformed);

        txtProductID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtProductID.addActionListener(this::txtProductIDActionPerformed);

        btnDeleteProduct.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnDeleteProduct.setText("Delete Product");
        btnDeleteProduct.addActionListener(this::btnDeleteProductActionPerformed);

        btnClear.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnAddProduct.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(this::btnAddProductActionPerformed);

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Size");

        jLabel1.setFont(new java.awt.Font("Consolas", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE PRODUCTS");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Category");

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Product ID");

        txtSize.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtSize.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtColor.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtColor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Product Name");

        txtPrice.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtProductName.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtProductName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Stock Quantity");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Colour");

        btnClose.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        cmbCategory.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casual Wear", "Formal Wear", "Sportswear", "Footwear", "Accessories" }));
        cmbCategory.addActionListener(this::cmbCategoryActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProductID)
                            .addComponent(txtProductName)
                            .addComponent(txtBrand)
                            .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSize)
                            .addComponent(txtColor)
                            .addComponent(txtPrice)
                            .addComponent(txtStock))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnViewProducts)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddProduct)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateProduct)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteProduct)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        // TODO add your handling code here:
            try {

           // Product ID is required for identifying the product
           if (txtProductID.getText().trim().isEmpty()) {

               javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Please select a product to update."
               );

               return;
           }

           // Read product details from the form
           int productID = Integer.parseInt(
                   txtProductID.getText().trim()
           );

           String productName = txtProductName.getText().trim();
           String brand = txtBrand.getText().trim();
           String categoryName = cmbCategory.getSelectedItem().toString();
           String size = txtSize.getText().trim();
           String color = txtColor.getText().trim();

           // Check required fields
           if (productName.isEmpty()
                   || brand.isEmpty()
                   || size.isEmpty()
                   || color.isEmpty()
                   || txtPrice.getText().trim().isEmpty()
                   || txtStock.getText().trim().isEmpty()) {

               javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Please fill all product details."
               );

               return;
           }

           // Convert category name to CategoryID
           int categoryID = getCategoryID(categoryName);

           // Convert price and stock
           double price = Double.parseDouble(
                   txtPrice.getText().trim()
           );

           int stock = Integer.parseInt(
                   txtStock.getText().trim()
           );

           // Validate values
           if (price < 0 || stock < 0) {

               javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Price and stock cannot be negative."
               );

               return;
           }

           // Create Product object
           model.Product product = new model.Product();

           product.setProductID(productID);
           product.setProductName(productName);
           product.setBrand(brand);
           product.setCategoryID(categoryID);
           product.setSize(size);
           product.setColor(color);
           product.setPrice(price);
           product.setStockQuantity(stock);

           // Update product through DAO
           dao.ProductDAO productDAO = new dao.ProductDAO();

           boolean success = productDAO.updateProduct(product);

           if (success) {

               javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Product updated successfully!"
               );

               // Refresh table
               loadProducts();

               // Clear fields
               clearFields();

           } else {

               javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Failed to update product."
               );
           }

       } catch (NumberFormatException e) {

           javax.swing.JOptionPane.showMessageDialog(
                   this,
                   "Please enter valid numbers for Product ID, Price and Stock."
           );

       } catch (Exception e) {

           javax.swing.JOptionPane.showMessageDialog(
                   this,
                   "Error updating product: " + e.getMessage()
           );
       }
    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
        // TODO add your handling code here:
        int row = tblProducts.getSelectedRow();

        if (row >= 0) {

            // Get product details from the selected table row
            txtProductID.setText(
                    tblProducts.getValueAt(row, 0).toString()
            );

            txtProductName.setText(
                    tblProducts.getValueAt(row, 1).toString()
            );

            txtBrand.setText(
                    tblProducts.getValueAt(row, 2).toString()
            );

            cmbCategory.setSelectedItem(
                    tblProducts.getValueAt(row, 3).toString()
            );

            txtSize.setText(
                    tblProducts.getValueAt(row, 4).toString()
            );

            txtColor.setText(
                    tblProducts.getValueAt(row, 5).toString()
            );

            txtPrice.setText(
                    tblProducts.getValueAt(row, 6).toString()
            );

            txtStock.setText(
                    tblProducts.getValueAt(row, 7).toString()
            );
        }
    }//GEN-LAST:event_tblProductsMouseClicked

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void btnViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductsActionPerformed
        // TODO add your handling code here:
        dao.ProductDAO productDAO = new dao.ProductDAO();

        java.util.ArrayList<model.Product> products =
                productDAO.getAllProducts();

        javax.swing.table.DefaultTableModel tableModel =
                (javax.swing.table.DefaultTableModel) tblProducts.getModel();

        tableModel.setRowCount(0);

        for (model.Product product : products) {

            String categoryName = getCategoryName(
                    product.getCategoryID()
            );

            tableModel.addRow(new Object[]{
                product.getProductID(),
                product.getProductName(),
                product.getBrand(),
                categoryName,
                product.getSize(),
                product.getColor(),
                product.getPrice(),
                product.getStockQuantity()
            });
        }
    }//GEN-LAST:event_btnViewProductsActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // TODO add your handling code here:
            try {

            // Product ID is required to identify the product
            if (txtProductID.getText().trim().isEmpty()) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Please select a product to delete."
                );

                return;
            }

            int productID = Integer.parseInt(
                    txtProductID.getText().trim()
            );

            // Ask for confirmation before deleting
            int confirmation = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete this product?",
                    "Confirm Delete",
                    javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (confirmation != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }

            // Delete product through DAO
            dao.ProductDAO productDAO = new dao.ProductDAO();

            boolean success = productDAO.deleteProduct(productID);

            if (success) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Product deleted successfully!"
                );

                // Refresh the table
                loadProducts();

                // Clear input fields
                clearFields();

            } else {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Failed to delete product."
                );
            }

        } catch (NumberFormatException e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a valid Product ID."
            );

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error deleting product: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
            try {

           // Read values entered by the user
           String productName = txtProductName.getText().trim();
           String brand = txtBrand.getText().trim();
           String categoryName = cmbCategory.getSelectedItem().toString();
           String size = txtSize.getText().trim();
           String color = txtColor.getText().trim();

           // Check required fields
           if (productName.isEmpty()
                   || brand.isEmpty()
                   || size.isEmpty()
                   || color.isEmpty()
                   || txtPrice.getText().trim().isEmpty()
                   || txtStock.getText().trim().isEmpty()) {

               javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Please fill all product details."
               );

               return;
           }

           // Convert category name into CategoryID
           int categoryID = getCategoryID(categoryName);

           // Convert price and stock values
           double price = Double.parseDouble(
                   txtPrice.getText().trim()
           );

           int stock = Integer.parseInt(
                   txtStock.getText().trim()
           );

           // Validate price and stock
           if (price < 0 || stock < 0) {

               javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Price and stock cannot be negative."
               );

               return;
           }

           // Create Product object
           model.Product product = new model.Product();

           product.setProductName(productName);
           product.setBrand(brand);
           product.setCategoryID(categoryID);
           product.setSize(size);
           product.setColor(color);
           product.setPrice(price);
           product.setStockQuantity(stock);

           // Save product using DAO
           dao.ProductDAO productDAO = new dao.ProductDAO();

           boolean success = productDAO.addProduct(product);

           if (success) {

               javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Product added successfully!"
               );

               // Refresh product table
               loadProducts();

               // Clear input fields
               clearFields();

           } else {

               javax.swing.JOptionPane.showMessageDialog(
                       this,
                       "Failed to add product."
               );
           }

       } catch (NumberFormatException e) {

           javax.swing.JOptionPane.showMessageDialog(
                   this,
                   "Please enter valid numbers for Price and Stock."
           );

       } catch (Exception e) {

           javax.swing.JOptionPane.showMessageDialog(
                   this,
                   "Error adding product: " + e.getMessage()
           );
       }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageProductsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JButton btnViewProducts;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
