public class ManagerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerDashboard.class.getName());

    
    /**
     * Creates new form ManagerDashboard
     */
    public ManagerDashboard(model.User user) {
        initComponents();
        
        setLocationRelativeTo(null);

        setTitle("Fashion Flair Boutique - Manager Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnManageProducts = new javax.swing.JButton();
        btnProcessPurchase = new javax.swing.JButton();
        btnSearchCategory = new javax.swing.JButton();
        btnManageStaff = new javax.swing.JButton();
        btnUpdatePrices = new javax.swing.JButton();
        btnPromotions = new javax.swing.JButton();
        btnSalesSummary = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("FASHION FLAIR BOUTIQUE");

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manager Dashboard ");

        btnManageProducts.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnManageProducts.setText("Manage Products");
        btnManageProducts.addActionListener(this::btnManageProductsActionPerformed);

        btnProcessPurchase.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnProcessPurchase.setText("Process Purchase");
        btnProcessPurchase.addActionListener(this::btnProcessPurchaseActionPerformed);

        btnSearchCategory.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnSearchCategory.setText("Search by Category");
        btnSearchCategory.addActionListener(this::btnSearchCategoryActionPerformed);

        btnManageStaff.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnManageStaff.setText("Manage Staff");
        btnManageStaff.addActionListener(this::btnManageStaffActionPerformed);

        btnUpdatePrices.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnUpdatePrices.setText("Update Prices");
        btnUpdatePrices.addActionListener(this::btnUpdatePricesActionPerformed);

        btnPromotions.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnPromotions.setText("Promotions");
        btnPromotions.addActionListener(this::btnPromotionsActionPerformed);

        btnSalesSummary.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnSalesSummary.setText("Sales Summary");
        btnSalesSummary.addActionListener(this::btnSalesSummaryActionPerformed);

        btnLogout.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProcessPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearchCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdatePrices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPromotions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalesSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(jLabel3))))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(btnManageProducts)
                .addGap(18, 18, 18)
                .addComponent(btnProcessPurchase)
                .addGap(18, 18, 18)
                .addComponent(btnSearchCategory)
                .addGap(18, 18, 18)
                .addComponent(btnManageStaff)
                .addGap(18, 18, 18)
                .addComponent(btnUpdatePrices)
                .addGap(18, 18, 18)
                .addComponent(btnPromotions)
                .addGap(18, 18, 18)
                .addComponent(btnSalesSummary)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductsActionPerformed
        // TODO add your handling code here:
        ManageProductsForm form = new ManageProductsForm();

            form.setVisible(true);
    }//GEN-LAST:event_btnManageProductsActionPerformed

    private void btnProcessPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessPurchaseActionPerformed
        // TODO add your handling code here:
        ProcessPurchaseForm form =
            new ProcessPurchaseForm(null);

            form.setVisible(true);
    }//GEN-LAST:event_btnProcessPurchaseActionPerformed

    private void btnSearchCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCategoryActionPerformed
        // TODO add your handling code here:
        String input = javax.swing.JOptionPane.showInputDialog(
            this,
            "Enter Category ID:\n"
            + "1 - Casual Wear\n"
            + "2 - Formal Wear\n"
            + "3 - Sportswear\n"
            + "4 - Footwear\n"
            + "5 - Accessories"
        );

        if (input == null) {
            return;
        }

        try {

            int categoryID = Integer.parseInt(input);

            if (categoryID < 1 || categoryID > 5) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Please enter a category number from 1 to 5."
                );

                return;
            }

            dao.ProductDAO productDAO =
                    new dao.ProductDAO();

            java.util.ArrayList<model.Product> products =
                    productDAO.searchByCategory(categoryID);

            if (products.isEmpty()) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "No products found in this category."
                );

                return;
            }

            StringBuilder result = new StringBuilder();

            for (model.Product product : products) {

                result.append("Product ID: ")
                        .append(product.getProductID())
                        .append("\n");

                result.append("Product Name: ")
                        .append(product.getProductName())
                        .append("\n");

                result.append("Brand: ")
                        .append(product.getBrand())
                        .append("\n");

                result.append("Size: ")
                        .append(product.getSize())
                        .append("\n");

                result.append("Color: ")
                        .append(product.getColor())
                        .append("\n");

                result.append("Price: Rs. ")
                        .append(product.getPrice())
                        .append("\n");

                result.append("Stock: ")
                        .append(product.getStockQuantity())
                        .append("\n");

                result.append("--------------------------------\n");
            }

            javax.swing.JTextArea textArea =
                    new javax.swing.JTextArea(result.toString());

            textArea.setEditable(false);

            javax.swing.JScrollPane scrollPane =
                    new javax.swing.JScrollPane(textArea);

            scrollPane.setPreferredSize(
                    new java.awt.Dimension(500, 400)
            );

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    scrollPane,
                    "Products by Category",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            } 
                catch (NumberFormatException e) {

                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a valid category number."
                );
            }
    }//GEN-LAST:event_btnSearchCategoryActionPerformed

    private void btnManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStaffActionPerformed
        // TODO add your handling code here:
        StaffManagementForm form =
            new StaffManagementForm();

            form.setVisible(true);
    }//GEN-LAST:event_btnManageStaffActionPerformed

    private void btnUpdatePricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePricesActionPerformed
        // TODO add your handling code here:
        UpdatePriceForm form =
            new UpdatePriceForm();

            form.setVisible(true);
    }//GEN-LAST:event_btnUpdatePricesActionPerformed

    private void btnPromotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromotionsActionPerformed
        // TODO add your handling code here:
        PromotionForm form =
            new PromotionForm();

            form.setVisible(true);
    }//GEN-LAST:event_btnPromotionsActionPerformed

    private void btnSalesSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesSummaryActionPerformed
        // TODO add your handling code here:
        SalesSummaryForm form =
            new SalesSummaryForm();

            form.setVisible(true);
    }//GEN-LAST:event_btnSalesSummaryActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
         int choice = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (choice == javax.swing.JOptionPane.YES_OPTION) {

            this.dispose();

            LoginForm loginForm =
                    new LoginForm();

            loginForm.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            model.User testUser = new model.User();
            testUser.setUserID(2);
            testUser.setFullName("Manager");
            testUser.setUsername("manager");
            testUser.setUserRole("Boutique Manager");

            new ManagerDashboard(testUser).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageProducts;
    private javax.swing.JButton btnManageStaff;
    private javax.swing.JButton btnProcessPurchase;
    private javax.swing.JButton btnPromotions;
    private javax.swing.JButton btnSalesSummary;
    private javax.swing.JButton btnSearchCategory;
    private javax.swing.JButton btnUpdatePrices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
