/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */
public class ProcessPurchaseForm extends javax.swing.JFrame {
    
    private model.User loggedUser;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProcessPurchaseForm.class.getName());

    /**
     * Creates new form ProcessPurchaseForm
     */
    public ProcessPurchaseForm(model.User user) {
    initComponents();

    this.loggedUser = user;

    setLocationRelativeTo(null);
    setTitle("Fashion Flair Boutique - Process Purchase");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        btnProcessPurchase = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("PROCESS CUSTOMER PURCHASE");

        txtProductID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtProductID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtQuantity.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnProcessPurchase.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnProcessPurchase.setText("Process Purchase");
        btnProcessPurchase.addActionListener(this::btnProcessPurchaseActionPerformed);

        btnClear.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Product ID");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnProcessPurchase)
                            .addGap(18, 18, 18)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(103, 103, 103))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcessPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessPurchaseActionPerformed
        // TODO add your handling code here:
        String productIDText =
            txtProductID.getText().trim();

        String quantityText =
                txtQuantity.getText().trim();

        // Check whether required fields are empty
        if (productIDText.isEmpty()
                || quantityText.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter Product ID and Quantity.",
                    "Validation Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        int productID;
        int quantity;

        // Convert text input into numbers
        try {

            productID =
                    Integer.parseInt(productIDText);

            quantity =
                    Integer.parseInt(quantityText);

        } catch (NumberFormatException e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Product ID and Quantity must be whole numbers.",
                    "Invalid Input",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Validate Product ID
        if (productID <= 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Product ID must be greater than 0.",
                    "Invalid Product ID",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Validate Quantity
        if (quantity <= 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Quantity must be greater than 0.",
                    "Invalid Quantity",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Get products from database
        dao.ProductDAO productDAO =
                new dao.ProductDAO();

        java.util.ArrayList<model.Product> products =
                productDAO.getAllProducts();

        model.Product selectedProduct = null;

        // Find the selected product
        for (model.Product product : products) {

            if (product.getProductID() == productID) {

                selectedProduct = product;
                break;
            }
        }

        // Check whether product exists
        if (selectedProduct == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Product not found.",
                    "Purchase Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Check available stock
        if (selectedProduct.getStockQuantity()
                < quantity) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Insufficient stock.\n"
                    + "Available Stock: "
                    + selectedProduct.getStockQuantity(),
                    "Stock Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        double unitPrice =
                selectedProduct.getPrice();

        double totalAmount =
                unitPrice * quantity;

        // Display purchase information
        String purchaseDetails =
                "Product: "
                + selectedProduct.getProductName()
                + "\nBrand: "
                + selectedProduct.getBrand()
                + "\nQuantity: "
                + quantity
                + "\nUnit Price: Rs. "
                + unitPrice
                + "\nTotal Amount: Rs. "
                + totalAmount;

        int confirmation =
                javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        purchaseDetails
                        + "\n\nConfirm this purchase?",
                        "Confirm Purchase",
                        javax.swing.JOptionPane.YES_NO_OPTION
                );

        // Stop if user cancels
        if (confirmation
                != javax.swing.JOptionPane.YES_OPTION) {

            return;
        }

        /*
         * Get the currently logged-in user.
         *
         * For this form, user ID 1 is used as the
         * Sales Assistant who processes the sale.
         */
        int userID = loggedUser.getUserID();

        // Process the sale using SaleDAO
        dao.SaleDAO saleDAO =
                new dao.SaleDAO();

        boolean success =
                saleDAO.processSale(
                        userID,
                        productID,
                        quantity,
                        unitPrice
                );

        if (success) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Purchase processed successfully!\n\n"
                    + "Product: "
                    + selectedProduct.getProductName()
                    + "\nQuantity: "
                    + quantity
                    + "\nTotal Amount: Rs. "
                    + totalAmount,
                    "Purchase Successful",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // Clear form after successful purchase
            txtProductID.setText("");
            txtQuantity.setText("");

            txtProductID.requestFocus();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Failed to process the purchase.\n"
                    + "Please try again.",
                    "Purchase Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnProcessPurchaseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtProductID.setText("");
        txtQuantity.setText("");

        txtProductID.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        model.User user = new model.User();
        user.setUserID(1);
        user.setFullName("Test User");
        user.setUsername("test");
        user.setUserRole("Sales Assistant");

        new ProcessPurchaseForm(user).setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnProcessPurchase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
