/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */

import javax.swing.JOptionPane;

public class PromotionForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PromotionForm.class.getName());

    /**
     * Creates new form PromotionForm
     */
    public PromotionForm() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        btnApplyDiscount = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE PROMOTIONS");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Product ID ");

        txtProductID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtProductID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Discount (%)");

        txtDiscount.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnApplyDiscount.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnApplyDiscount.setText("Apply Discount");
        btnApplyDiscount.addActionListener(this::btnApplyDiscountActionPerformed);

        btnClear.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnApplyDiscount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApplyDiscount)
                    .addComponent(btnClear))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyDiscountActionPerformed
        // TODO add your handling code here:

        // Get values entered by the manager
        String productIDText =
                txtProductID.getText().trim();

        String discountText =
                txtDiscount.getText().trim();


        // Validate empty fields
        if (productIDText.isEmpty()
                || discountText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Product ID and Discount.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        int productID;
        double discountPercent;


        // Convert text values into numbers
        try {

            productID =
                    Integer.parseInt(productIDText);

            discountPercent =
                    Double.parseDouble(discountText);

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Product ID must be a whole number\n"
                    + "and discount must be a valid number.",
                    "Invalid Input",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        // Validate Product ID
        if (productID <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Product ID must be greater than 0.",
                    "Invalid Product ID",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        // Discount must be between 0 and 100
        if (discountPercent <= 0
                || discountPercent > 100) {

            JOptionPane.showMessageDialog(
                    this,
                    "Discount must be between 1% and 100%.",
                    "Invalid Discount",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        // Create ProductDAO object
        dao.ProductDAO productDAO =
                new dao.ProductDAO();


        // Find the selected product
        java.util.ArrayList<model.Product> products =
                productDAO.getAllProducts();

        model.Product selectedProduct = null;

        for (model.Product product : products) {

            if (product.getProductID() == productID) {

                selectedProduct = product;
                break;
            }
        }


        // Check whether product exists
        if (selectedProduct == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Product ID " + productID
                    + " was not found.",
                    "Product Not Found",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        // Store current price
        double currentPrice =
                selectedProduct.getPrice();


        // Calculate discounted price
        double discountAmount =
                currentPrice * discountPercent / 100;

        double newPrice =
                currentPrice - discountAmount;


        // Ask manager for confirmation
        int confirmation =
                JOptionPane.showConfirmDialog(
                        this,
                        "Product: "
                        + selectedProduct.getProductName()
                        + "\n\n"
                        + "Current Price: Rs. "
                        + currentPrice
                        + "\n"
                        + "Discount: "
                        + discountPercent
                        + "%"
                        + "\n"
                        + "New Price: Rs. "
                        + newPrice
                        + "\n\n"
                        + "Apply this discount?",
                        "Confirm Promotion",
                        JOptionPane.YES_NO_OPTION
                );


        if (confirmation != JOptionPane.YES_OPTION) {

            return;
        }


        // Apply discount to database
        boolean success =
                productDAO.applyDiscount(
                        productID,
                        discountPercent
                );


        if (success) {

            JOptionPane.showMessageDialog(
                    this,
                    "Promotion applied successfully!\n\n"
                    + "Product: "
                    + selectedProduct.getProductName()
                    + "\n"
                    + "Discount: "
                    + discountPercent
                    + "%"
                    + "\n"
                    + "New Price: Rs. "
                    + newPrice,
                    "Promotion Successful",
                    JOptionPane.INFORMATION_MESSAGE
            );


            // Clear fields
            txtProductID.setText("");
            txtDiscount.setText("");

            txtProductID.requestFocus();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to apply promotion.",
                    "Promotion Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnApplyDiscountActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtProductID.setText("");
        txtDiscount.setText("");

        txtProductID.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PromotionForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyDiscount;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtProductID;
    // End of variables declaration//GEN-END:variables
}
