public class SalesAssistantDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalesAssistantDashboard.class.getName());

    /**
     * Creates new form SalesAssistantDashboard
     */
    private model.User loggedUser;

    public SalesAssistantDashboard(model.User user) {

    initComponents();

    this.loggedUser = user;

    setLocationRelativeTo(null);

    setTitle("Fashion Flair Boutique - Sales Assistant Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("FASHION FLAIR BOUTIQUE");

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Sales Assistant Dashboard ");

        jButton1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton1.setText("View Products");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton2.setText("Add Product");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton3.setText("Search by Category");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton4.setText("Process Purchase");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton5.setText("Logout");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(149, 149, 149))))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    dao.ProductDAO productDAO = new dao.ProductDAO();

    java.util.ArrayList<model.Product> products =
            productDAO.getAllProducts();

    StringBuilder output = new StringBuilder();

    output.append("FASHION FLAIR BOUTIQUE\n");
    output.append("==============================================\n\n");

    if (products.isEmpty()) {

        output.append("No products found.");

    } else {

        for (model.Product product : products) {

            output.append("Product ID : ")
                    .append(product.getProductID())
                    .append("\n");

            output.append("Product    : ")
                    .append(product.getProductName())
                    .append("\n");

            output.append("Brand      : ")
                    .append(product.getBrand())
                    .append("\n");

            output.append("Size       : ")
                    .append(product.getSize())
                    .append("\n");

            output.append("Color      : ")
                    .append(product.getColor())
                    .append("\n");

            output.append("Price      : Rs. ")
                    .append(product.getPrice())
                    .append("\n");

            output.append("Stock      : ")
                    .append(product.getStockQuantity())
                    .append("\n");

            output.append("----------------------------------------------\n");
        }
    }

    javax.swing.JTextArea textArea =
            new javax.swing.JTextArea(output.toString());

    textArea.setEditable(false);

    textArea.setFont(
            new java.awt.Font(
                    "Monospaced",
                    java.awt.Font.PLAIN,
                    14
            )
    );

    javax.swing.JScrollPane scrollPane =
            new javax.swing.JScrollPane(textArea);

    scrollPane.setPreferredSize(
            new java.awt.Dimension(600, 400)
    );

    javax.swing.JOptionPane.showMessageDialog(
            this,
            scrollPane,
            "Available Products",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         AddProductForm addProductForm =
            new AddProductForm();

        addProductForm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String categoryName = javax.swing.JOptionPane.showInputDialog(
            this,
            "Enter Category:\n\n"
            + "1 - Casual Wear\n"
            + "2 - Formal Wear\n"
            + "3 - Sportswear\n"
            + "4 - Footwear\n"
            + "5 - Accessories",
            "Search Products by Category",
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (categoryName == null || categoryName.trim().isEmpty()) {
            return;
        }

        int categoryID;

        try {
            categoryID = Integer.parseInt(categoryName.trim());
        } catch (NumberFormatException e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a valid category number.",
                    "Invalid Category",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        if (categoryID < 1 || categoryID > 5) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a number between 1 and 5.",
                    "Invalid Category",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        dao.ProductDAO productDAO =
                new dao.ProductDAO();

        java.util.ArrayList<model.Product> products =
                productDAO.searchByCategory(categoryID);

        StringBuilder output =
                new StringBuilder();

        output.append("FASHION FLAIR BOUTIQUE\n");
        output.append("PRODUCTS BY CATEGORY\n");
        output.append("==============================================\n\n");

        if (products.isEmpty()) {

            output.append("No products found in this category.");

        } else {

            for (model.Product product : products) {

                output.append("Product ID : ")
                        .append(product.getProductID())
                        .append("\n");

                output.append("Product    : ")
                        .append(product.getProductName())
                        .append("\n");

                output.append("Brand      : ")
                        .append(product.getBrand())
                        .append("\n");

                output.append("Size       : ")
                        .append(product.getSize())
                        .append("\n");

                output.append("Color      : ")
                        .append(product.getColor())
                        .append("\n");

                output.append("Price      : Rs. ")
                        .append(product.getPrice())
                        .append("\n");

                output.append("Stock      : ")
                        .append(product.getStockQuantity())
                        .append("\n");

                output.append("----------------------------------------------\n");
            }
        }

        javax.swing.JTextArea textArea =
                new javax.swing.JTextArea(
                        output.toString()
                );

        textArea.setEditable(false);

        textArea.setFont(
                new java.awt.Font(
                        "Monospaced",
                        java.awt.Font.PLAIN,
                        14
                )
        );

        javax.swing.JScrollPane scrollPane =
                new javax.swing.JScrollPane(textArea);

        scrollPane.setPreferredSize(
                new java.awt.Dimension(600, 400)
        );

        javax.swing.JOptionPane.showMessageDialog(
                this,
                scrollPane,
                "Search Results",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ProcessPurchaseForm purchaseForm =
             new ProcessPurchaseForm(loggedUser);

        purchaseForm.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int result = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (result == javax.swing.JOptionPane.YES_OPTION) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "You have been logged out successfully.",
                    "Logout",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // Close the current dashboard
            this.dispose();

            // Return to Login Form
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

        /**
     * Main method for running the Sales Assistant Dashboard
     * directly from NetBeans.
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                // Create a temporary user for direct testing.
                model.User testUser = new model.User();

                testUser.setUserID(1);
                testUser.setFullName("Nimal Perera");
                testUser.setUsername("nimal");
                testUser.setUserRole("Sales Assistant");

                // Open the Sales Assistant Dashboard.
                new SalesAssistantDashboard(testUser)
                        .setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}


