/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */

import javax.swing.JOptionPane;

public class UpdatePriceForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdatePriceForm.class.getName());

    /**
     * Creates new form UpdatePriceForm
     */
    public UpdatePriceForm() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        txtNewPrice = new javax.swing.JTextField();
        btnUpdatePrice = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 2, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE PRODUCT PRICE");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Product ID");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("New Price");

        txtProductID.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtProductID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProductID.addActionListener(this::txtProductIDActionPerformed);

        txtNewPrice.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtNewPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnUpdatePrice.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnUpdatePrice.setText("Update Price");
        btnUpdatePrice.addActionListener(this::btnUpdatePriceActionPerformed);

        btnClear.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUpdatePrice))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtProductID)
                        .addComponent(txtNewPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProductID, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdatePrice)
                    .addComponent(btnClear))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtProductID.setText("");
        txtNewPrice.setText("");

        txtProductID.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePriceActionPerformed
        // TODO add your handling code here:                                             

        // Get values entered by the manager
        String productIDText =
                txtProductID.getText().trim();

        String newPriceText =
                txtNewPrice.getText().trim();


        // Check whether both fields are filled
        if (productIDText.isEmpty()
                || newPriceText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Product ID and New Price.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        int productID;
        double newPrice;


        // Convert text values into numeric values
        try {

            productID =
                    Integer.parseInt(productIDText);

            newPrice =
                    Double.parseDouble(newPriceText);

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Product ID must be a whole number\n"
                    + "and price must be a valid number.",
                    "Invalid Input",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        // Validate Product ID
        if (productID <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Product ID must be greater than 0.",
                    "Invalid Product ID",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        // Validate new price
        if (newPrice <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "New price must be greater than 0.",
                    "Invalid Price",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        // Create ProductDAO object
        dao.ProductDAO productDAO =
                new dao.ProductDAO();


        // Get all products from the database
        java.util.ArrayList<model.Product> products =
                productDAO.getAllProducts();


        // Find the selected product
        model.Product selectedProduct = null;

        for (model.Product product : products) {

            if (product.getProductID() == productID) {

                selectedProduct = product;
                break;
            }
        }


        // Check whether the product exists
        if (selectedProduct == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Product ID " + productID
                    + " was not found.",
                    "Product Not Found",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }


        // Store the current price
        double currentPrice =
                selectedProduct.getPrice();


        // Show confirmation before updating
        int confirmation =
                JOptionPane.showConfirmDialog(
                        this,
                        "Product: "
                        + selectedProduct.getProductName()
                        + "\n\n"
                        + "Current Price: Rs. "
                        + currentPrice
                        + "\n"
                        + "New Price: Rs. "
                        + newPrice
                        + "\n\n"
                        + "Do you want to update this price?",
                        "Confirm Price Update",
                        JOptionPane.YES_NO_OPTION
                );


        if (confirmation != JOptionPane.YES_OPTION) {

            return;
        }


        // Update the price in the database
        boolean success =
                productDAO.updatePrice(
                        productID,
                        newPrice
                );


        if (success) {

            JOptionPane.showMessageDialog(
                    this,
                    "Product price updated successfully!\n\n"
                    + "Product: "
                    + selectedProduct.getProductName()
                    + "\n"
                    + "Old Price: Rs. "
                    + currentPrice
                    + "\n"
                    + "New Price: Rs. "
                    + newPrice,
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
            );


            // Clear fields after successful update
            txtProductID.setText("");
            txtNewPrice.setText("");

            txtProductID.requestFocus();


        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to update product price.",
                    "Update Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnUpdatePriceActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdatePriceForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdatePrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNewPrice;
    private javax.swing.JTextField txtProductID;
    // End of variables declaration//GEN-END:variables
}
